#pragma once

namespace ForradiaLang
{
    enum class TokenTypes
    {
        Identifier,
        Number,
        String,
        Plus,
        Minus,
        Star,
        Slash,
        Percent,
        Equals,
        GreaterThan,
        GreaterOrEqual,
        LessThan,
        LeftParen,
        RightParen,
        LeftBracket,
        RightBracket,
        Dot,
        Comma,
        Newline,
        If,
        Then,
        Else,
        ElseIf,
        And,
        Or,
        End,
        Print,
        Int,
        Double,
        For,
        To,
        Next,
        Continue,
        Fn,
        Class,
        Import,
        Scene,
        Update,
        OnMouseDown,
        OnKeyDown,
        OnEnter
    };
}